  <body>
    <form
      action="https://formsubmit.co/ajax/nickolas@tigercodes.com.br"
      method="POST"
      data-form
    >
      <label for="nome">Nome</label>
      <input type="text" name="nome" id="nome" required />
      <label for="email">E-mail</label>
      <input type="email" name="email" id="email" required />
      <label for="mensagem">Mensagem</label>
      <textarea name="mensagem" id="mensagem" required></textarea>
      <button type="submit" data-button>Enviar</button>
    </form>
  </body>
</html>
