 <body>
    <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
          <form action="/autenticar" method="post" class="sign-in-form">
            <h2 class="title">Login</h2>
            <?php if(isset($_GET['registro']) && $_GET['registro'] == 'sucesso') : ?>
              <p style="color:green;">Registrado com sucesso!</p>
            <?php endif; ?>
            <?php if($this->view->erroCadastro) : ?>
              <p style="color:red;">Erro ao tentar realizar o cadastro. Verifique as credenciais e tente novamente</p>
            <?php endif;?>
            <?php if(isset($_GET['login']) && $_GET['login'] == 'erro') : ?>
              <p style="color:red;">Erro ao tentar realizar login. Verifique as credenciais e tente novamente</p>
            <?php endif; ?>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="E-mail" name="email" />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Senha" name="senha"/>
            </div>
            <input type="submit" value="Entrar" class="btn solid" />

            <p class="social-text">Ou entre com essas plataformas</p>
            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </form>


          <form action="/cadastrar" method="post" class="sign-up-form">
            <h2 class="title">Cadastro</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input name="nome" type="text" placeholder="Usuário" />
            </div>
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              <input name="email" type="email" placeholder="Email" />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input name="senha" type="password" placeholder="Senha" />
            </div>
            <input type="submit" value="Cadastrar" class="btn solid" />

            <p class="social-text">Ou se cadastre com essas plataformas</p>
            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </form>
        </div>
      </div>
      <div class="panels-container">

        <div class="panel left-panel">
            <div class="content">
                <h3>Novo aqui?</h3>
                <p>Crie uma conta para comprar e escolher seus tênis favoritos.</p>
                <button class="btn transparent" id="sign-up-btn">Cadastrar-se</button>
            </div>
            <img src="Imagens/imgLogin/log.svg" class="image" alt="">
        </div>

        <div class="panel right-panel">
            <div class="content">
                <h3>Já tem uma conta?</h3>
                <p>Clique aqui para entrar </p>
                <button class="btn transparent" id="sign-in-btn">Entrar</button>
            </div>
            <img src="Imagens/imgLogin/register.svg" class="image" alt="">
        </div>
      </div>
    </div>

    <script src="Js/appLogin.js"></script>
  </body>
</html>
