
<body>

<div class="container">
  <nav>
        <a href="/" class="brand">JVRB</a>
        <a href="#">
            <span class="material-symbols-outlined">
                shopping_bag
            </span>

        </a>
    </nav>


  <main>
<div>
    <span>HOMENS-</span>
    <h1 class="title">
        <span class="titleText">
            Red Nike Jordan Max Aura 3
        </span>
        <span class="titleOverlay"></span>
    </h1>
    <p class="description">
       
    </p>
    <div class="thumbs">
        <img src="imgProduto/thumbs/shoe1-1/img1.jpg"
        class="thumb-active"/>
        <img src="imgProduto/thumbs/shoe1-1/img2.jpg"/>
        <img src="imgProduto/thumbs/shoe1-1/img3.jpg"/>
        <img src="imgProduto/thumbs/shoe1-1/img4.jpg"/>
    </div>
</div>
<div class="showcase">
    <div>
        <img src="imgProduto/showcase/shoe1-1/img1.png"/>
        <div class="shadow"></div>
    </div>
</div>
<div class="options">
    <h4>TAMANHO</h4>
    <ul class="sizes">
        <li class="size-active">37</li>
        <li>38</li>
        <li>39</li>
        <li>40</li>
        <li>41</li>

    </ul>

    <div class="reviews">
        <h4>Reviews</h4>     
        <ul class="stars">
            <li>
                <span class="material-symbols-outlined">
                    star
                </span>
            </li>
            <li>
                <span class="material-symbols-outlined">
                    star
                </span>
            </li>
            <li>
                <span class="material-symbols-outlined">
                    star
                </span>
            </li>
                <li>
                    <span class="material-symbols-outlined">
                        star
                    </span>
                </li>
                    <li>
                        <span class="material-symbols-outlined">
                            star_outline
                        </span>
                    </li>
        </ul>
    </div>
    <div class="pricing">
        <h4>PREÇÕ</h4>
        <h4 class="price">R$90</h4>
    </div>
    <div class="colors">
        <h4>Colors</h4>
        <ul>
            <li class="color color-active"></li>
            <li class="color"></li>
        </ul>
    </div>
</div>
</main>
<section class="bar-bottom">
    <div>
        <a href="#">
            <span class="material-symbols-outlined">
                play_arrow
            </span>
            <span>Play Video</span>
            
        </a>
    </div>
    
    <div class="controls">
<div class="arrows">
    <span class="material-symbols-outlined
    arr-right">
        arrow_right_alt
    </span>
    <span class="material-symbols-outlined
    arr-left">
        arrow_right_alt
    </span>
</div>
<div>
    

    <small class="shoe-num">01</small>
    <div class="pagination">
        <span class="pag pag-active"></span>
        <span class="pag"></span>
        <span class="pag"></span>
    </div>
<small class="shoe-total">03</small>
</div>
  </div>
    <div class="cart">
        <button>Adicionar ao Carrinho</button>
        <span class="material-symbols-outlined">
            favorite_border
        </span>
    </div>
    
<script src="Js/Produto.js"></script>
    
</section>
</div>
</body>
</html>

