
	<main class="page">
	 	<section class="shopping-cart dark">
	 		<div class="container">
		        <div class="block-heading">
		          <h2>Carrinho de Compras</h2>
		          <p>Veja os produtos que você escolheu logo abaixo!.</p>
		        </div>
		        <div class="content">
	 				<div class="row">
	 					<div class="col-md-12 col-lg-8">
	 						<div class="items">
				 				<!--
									Implantado dinamicamente com jquery

				 				<div class="product">
				 					<div class="row">
					 					<div class="col-md-3">
					 						<img class="img-fluid mx-auto d-block image" src="assets/img/img2.png">
					 					</div>
					 					<div class="col-md-8">
					 						<div class="info">
						 						<div class="row">
							 						<div class="col-md-5 product-name">
							 							<div class="product-name">
								 							<a href="#">Tênis</a>
								 							<div class="product-info">
																<div> Red Nike Jordan Max Aura 3<span class="value"></span></div>
																<div> <span class="value"></span></div>
																<div> <span class="value"></span></div>
									 						</div>
									 					</div>
							 						</div>
							 						<div class="col-md-4 quantity">
							 							<label for="quantity">Quantidade:</label>
							 							<input id="quantity" type="number" value ="1" class="form-control quantity-input">
							 						</div>
							 						<div class="col-md-3 price">
							 							<span>$120</span>
							 						</div>
							 					</div>
							 				</div>
					 					</div>
					 				</div>
				 				</div>-->
				 				
				 			</div>
			 			</div>
			 			<div class="col-md-12 col-lg-4">
			 				<div class="summary">
			 					<h3>Summary</h3>
			 					<div class="summary-item"><span class="text">Subtotal</span><span class="price">R$360</span></div>
								 <div class="summary-item"><span class="text">Desconto</span><span class="price">R$360</span></div>
								 <div class="summary-item"><span class="text">Cupom</span><span class="price">R$360</span></div>
			 					<div class="summary-item"><span class="text">Total</span><span class="price">R$360</span></div>
								<form action="">
									<button type="submit" class="btn btn-primary btn-lg btn-block">Finalizar Compra</button>
								</form>
				 			</div>
			 			</div>
		 			</div> 
		 		</div>
	 		</div>
		</section>
	</main>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

