<?php
    include '../App/Views/nav.phtml'
  ?>
<section class="home" id="home">
<div class="slide-container active">
 <div class="slide">
  <div class="content">
   <span>Nike Free Metcon Vermelho</span>
   <p>Sapato Nike da linha Free Metcon, feito para corrida ou treino</p>
   <a href="/exposicao" class="btn">EXPOSIÇÃO</a>
  </div>
  <div class="image">
   <img src="Imagens/imgHome/home-shoe-1.png" class="shoe" alt="">
   <img src="Imagens/imgHome/home-text-1.png" class="text" alt="">
  </div>
 </div>
</div>
<div class="slide-container">
 <div class="slide">
  <div class="content">
   <span>Nike Free Metcon Azul</span>
   <p>Sapato Nike da linha Free Metcon, feito para corrida ou treino.</p>
   <a href="/exposicao" class="btn">EXPOSIÇÃO</a>
  </div>
  <div class="image">
   <img src="Imagens/imgHome/home-shoe-2.png" class="shoe" alt="">
   <img src="Imagens/imgHome/home-text-2.png" class="text" alt="">
  </div>
 </div>
</div>
<div class="slide-container">
 <div class="slide">
  <div class="content">
   <span>Nike Free Metcon Amarelo</span>
   <p>Sapato Nike da linha Free Metcon, feito para corrida ou treino.</p>
   <a href="/exposicao" class="btn">EXPOSIÇÃO</a>
  </div>
  <div class="image">
   <img src="Imagens/imgHome/home-shoe-3.png" class="shoe" alt="">
   <img src="Imagens/imgHome/home-text-3.png" class="text" alt="">
  </div>
 </div>
</div>
<div id="prev" class="fas fa-chevron-left" onclick="prev()"></div>
<div id="next" class="fas fa-chevron-right" onclick="next()"></div>

</section>






<section class="service">
<div class="box-container">

 <div class="box">
  <i class="fa fa-shipping-fast"></i>
  <h3>Entregas rápidas</h3>
  <p>O prazo estimado é de 1 semana até 1 mês dependendo da sua localização</p>
 </div>

 <div class="box">
  <i class="fa fa-undo"></i>
  <h3>Troca de produtos</h3>
  <p>o prazo de troca é até 10 dias após o uso</p>
 </div>

 <div class="box">
  <i class="fa fa-headset"></i>
  <h3>Suporte</h3>
  <p>Teremos equipes nos 7 dias da semana até as 24 Horas(24/7).</p>
 </div>

</div>
</section>



<section class="products" id="products">
<h1 class="heading"> ÚLTIMOS  <span>PRODUTOS</span> </h1>
<div class="box-container">
 <div class="box">
  <div class="icons">
   <a href="#" class="fas fa-heart"></a>
   <a href="#" class="fas fa-share"></a>
   <a href="#" class="fas fa-eye"></a>
  </div>
  <img src="img/showcase/shoe1-1/img1.png" alt="">
  <div class="content">
   <h3>Red Nike Jordan Max Aura 3</h3>
   <div class="price">R$90,00 <span>R$150.99</span></div>
   <div class="stars">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="far fa-star"></i>
   </div>
   <form action="/produto/show" method="get">
      <input type="hidden" name="id_produto" value="1">
      <button type="submit" class="btn">Ver Produto</button>
   </form>
  </div>
 </div>
 <div class="box">
  <div class="icons">
   <a href="#" class="fas fa-heart"></a>
   <a href="#" class="fas fa-share"></a>
   <a href="#" class="fas fa-eye"></a>
  </div>
  <img src="img/showcase/shoe1-2/img1.png" alt="">
  <div class="content">
   <h3>Black Nike Jordan Max Aura 3</h3>
   <div class="price">R$120,00 <span>R$150.99</span></div>
   <div class="stars">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="far fa-star"></i>
   </div>
   <form action="/produto/show" method="get">
      <input type="hidden" name="id_produto" value="2">
      <button type="submit" class="btn">Ver Produto</button>
   </form>
  </div>
 </div>
 <div class="box">
  <div class="icons">
   <a href="#" class="fas fa-heart"></a>
   <a href="#" class="fas fa-share"></a>
   <a href="#" class="fas fa-eye"></a>
  </div>
  <img src="img/showcase/shoe2-1/img1.png" alt="">
  <div class="content">
   <h3>Nike Air Max 95</h3>
   <div class="price">R$200,00 <span>R$240,00</span></div>
   <div class="stars">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="far fa-star"></i>
   </div>
   <form action="/produto/show" method="get">
      <input type="hidden" name="id_produto" value="3">
      <button type="submit" class="btn">Ver Produto</button>
   </form>
  </div>
 </div>
 <div class="box">
  <div class="icons">
   <a href="#" class="fas fa-heart"></a>
   <a href="#" class="fas fa-share"></a>
   <a href="#" class="fas fa-eye"></a>
  </div>
  <img src="img/showcase/shoe2-2/img1.png" alt="">
  <div class="content">
   <h3>Nike Air Max 97</h3>
   <div class="price">R$170,00 <span>R$200,00</span></div>
   <div class="stars">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="far fa-star"></i>
   </div>
   <form action="/produto/show" method="get">
      <input type="hidden" name="id_produto" value="4">
      <button type="submit" class="btn">Ver Produto</button>
   </form>
  </div>
 </div>
 <div class="box">
  <div class="icons">
   <a href="#" class="fas fa-heart"></a>
   <a href="#" class="fas fa-share"></a>
   <a href="#" class="fas fa-eye"></a>
  </div>
  <img src="img/showcase/shoe3-1/img1.png" alt="">
  <div class="content">
   <h3>Nike Jordan Delta 2 Black Preta </h3>
   <div class="price">R$140,00 <span>R$180,00</span></div>
   <div class="stars">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="far fa-star"></i>
   </div>
   <form action="/produto/show" method="get">
      <input type="hidden" name="id_produto" value="5">
      <button type="submit" class="btn">Ver Produto</button>
   </form>
  </div>
 </div>
 <div class="box">
  <div class="icons">
   <a href="#" class="fas fa-heart"></a>
   <a href="#" class="fas fa-share"></a>
   <a href="#" class="fas fa-eye"></a>
  </div>
  <img src="img/showcase/shoe3-2/img1.png" alt="">
  <div class="content">
   <h3>Tênis Jordan Delta 2</h3>
   <div class="price">R$250,99 <span>R$300.00</span></div>
   <div class="stars">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="far fa-star"></i>
   </div>
   <form action="/produto/show" method="get">
      <input type="hidden" name="id_produto" value="6">
      <button type="submit" class="btn">Ver Produto</button>
   </form>
  </div>
 </div>
</div>

</section>


<section class="review" id="review">
<h1 class="heading"> AVALIAÇÕES DE <span>CLIENTES</span></h1>
<div class="box-container">
 <div class="box">
  <img src="Imagens/imgHome/pic1.png" alt="">
  <h2>Angélica</h2>
  <p>MEU FILHO AMOOOU!!!!
      SUPER INDICO PARA QUEM BUSCA CONFORTO E PRATICIDADE
  </p>
  <div class="stars">
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
  </div>
 </div>
 <div class="box">
  <img src="Imagens/imgHome/pic2.png" alt="">
  <h2>Marcos</h2>
  <p>Confortáve, custo bom, Nota 9 👍</p>
  <div class="stars">
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star-half-alt"></i>
  </div>
 </div>
 <div class="box">
  <img src="Imagens/imgHome/pic3.png" alt="">
  <h2>Roberto</h2>
  <p>De um tempo pra cá estava atrás de um tênis para corrida, vi que escolhi a empresa certa!</p>
  <div class="stars">
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star"></i>
   <i class="fa fa-star-half-alt"></i>
  </div>
 </div>
</div>
</section>




<section class="newsletter">
<div class="content">
 <h3>Entre em contato!</h3>
 <p>Digite seu e-mail abaixo caso queira entrar em contato conosco ou receber notícias de nossa loja</p>
 <form action="">
  <input type="email" placeholder="Digite seu E-mail" class="box">
  <input type="submit" value="Enviar" class="btn">
 </form>
</div>
</section>







<section class="footer">

<div class="box-container">

 

 <div class="box">
  <h3>Explore Mais</h3>
  <a href="/">home</a>
  <a href="/login">Login</a>
  <a href="/login">Cadastro</a>
  <a href="/contato">Contato</a>
 </div>

 <div class="box">
  <h3>Links Extras</h3>
  <a href="#">Meus pedidos</a>
 </div>

 <div class="box">
  <h3>Siga-nos</h3>
  <a href="#">facebook</a>
  <a href="#">twitter</a>
  <a href="#">instagram</a>
  
 </div>
 

</section>





<div vw class="enabled">
<div vw-access-button class="active"></div>
<div vw-plugin-wrapper>
  <div class="vw-plugin-top-wrapper"></div>
</div>
</div>
<script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
<script>
new window.VLibras.Widget('https://vlibras.gov.br/app');
</script>
<script src="Js/indexHome.js"></script>
</body>
