
		<main>
			<div class="container-img">
				<img 
					src="/<?=$this->view->img_tenis?>"
					alt="imagen-producto"
					class="imagem-reduzida"
				/>
			</div>
			<div class="container-info-product">
				<div class="container-price">
					<p id="nome-tenis"><?=$this->view->nome_tenis;?></p>
					<p id="preco-tenis">R$<?=$this->view->preco_tenis?></p>
				</div>

				<div class="container-details-product">

					<div class="form-group">
						<label for="size">Tamanho</label>
						<select name="size" id="size">
							<option disabled selected value="">
								Escolha uma opção
							</option>
							<option value="40">40</option>
							<option value="42">42</option>
							<option value="43">43</option>
							<option value="44">44</option>
						</select>
					</div>

					</div>

					<div class="container-add-cart">
					<form action="/adicionar_carrinho" method="post">
					<button type="submit" class="btn-add-to-cart">
						<i class="fa-solid fa-plus"></i>
						<input type="hidden" name="id_produto" value="<?=$this->view->id_produto?>">
						Adicionar ao Carrinho de Compras.
					</button>
					</form>	
					</div>

				<div class="container-description">
					<div class="title-description">
						<h4>Descrição</h4>
						<i class="fa-solid fa-chevron-down"></i>
					</div>
					<div class="text-description">
						<p>
							Leve um pedaço da história para as ruas urbanas da cidade ao calçar os tênis masculinos nike jordan max aura 3
						</p>
					</div>
				</div>

				

				
		</main>

	
		<script
			src="https://kit.fontawesome.com/81581fb069.js"
			crossorigin="anonymous"
		></script>
