<div class="container">

    <form action="/pagamento_concluido">

        <div class="row">

            <div class="col">

                <h3 class="title">Dados do Cliente</h3>

                <div class="inputBox">
                    <span>Nome Completo :</span>
                    <input type="text" placeholder="Vitor Rosario Silva">
                </div>
                
                
                <div class="inputBox">
                    <span>Cidade :</span>
                    <input type="text" placeholder="Rio de Janeiro">
                </div>

                <div class="flex">
                    <div class="inputBox">
                        <span>Rua :</span>
                        <input type="text" placeholder="Rua...">
                    </div>
                    <div class="inputBox">
                        <span>Número(Casa) :</span>
                        <input type="text" placeholder="000 000">
                    </div>

                    
                </div>

                <div class="inputBox">
                    <span>Vencimento:</span>
                    <input type="text" placeholder="Janeiro">
                </div>

                <div class="flex">
                    <div class="inputBox">
                        <span>Ano de Vencimento :</span>
                        <input type="number" placeholder="02/28">
                    </div>
                    <div class="inputBox">
                        <span>CVV :</span>
                        <input type="text" placeholder="000">
                    </div>
                </div>
            </div>

            <div class="col">

                <h3 class="title">Pagamento</h3>

                <div class="inputBox">
                    <span>Cartões Aceitos :</span>
                    <img src="images/card_img.png" alt="">
                </div>
                <div class="inputBox">
                    <span>Nome do Cartão:</span>
                    <input type="text" placeholder="MasterCard...">
                </div>
                <div class="inputBox">
                    <span>Numero do Cartão :</span>
                    <input type="number" placeholder="1111-2222-3333-4444">
                </div>
                

            </div>
    
        </div>

            <button type="submit" class="submit-btn">Confirmar Pagamento</button>

    </form>

</div>    
