<header>

<div id="menu-bar" class="fas fa-bars"></div>
<a href="#home" class="logo">JVRB</a>
<nav class="navbar">
 <a href="/">home</a>
 <?php if($this->view->logado == false) : ?>
 <a href="/login">login</a>
 <?php endif; ?>
 <?php if($this->view->logado == false) : ?>
 <a href="/login">Cadastro</a>
 <?php endif; ?>
 <a href="/contato">Contato</a>
 <?php if($this->view->logado): ?>
 <a href="/sair">Sair</a>
 <?php endif; ?>
</nav>

<div class="icons">
 <a href="/carrinho" class="fas fa-shopping-cart"></a>
 <a href="#" class="fas fa-user"></a>
 <?php if($this->view->logado): ?>
 <p>Olá, <?=$this->view->info_usuario['nome']?>!</p>
 <?php endif; ?>
</div>
</header>